# Generated by Django 2.0 on 2018-11-21 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('nota', models.IntegerField()),
                ('id_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='team.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level_asses', models.CharField(choices=[('P', 'Participant'), ('D', 'Disqualified'), ('W', 'Winner'), {'I', 'Invited'}], max_length=50)),
                ('id_hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competicoes.Hackathon')),
                ('id_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('activities', models.ManyToManyField(to='competicoes.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('winners', models.ManyToManyField(to='competicoes.Activity')),
            ],
        ),
        migrations.AddField(
            model_name='phase',
            name='awards',
            field=models.ManyToManyField(to='competicoes.Premium'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='phases',
            field=models.ManyToManyField(to='competicoes.Phase'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='team_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='team.Team'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='teams',
            field=models.ManyToManyField(related_name='teams', through='competicoes.Participation', to='team.Team'),
        ),
    ]
