# Generated by Django 2.0 on 2018-11-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.CharField(max_length=50)),
                ('level_asses', models.CharField(choices=[('U', 'User'), ('A', 'Admin'), ('I', 'Invited')], max_length=50)),
                ('id_team', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
